== addon-saphcp
:idprefix: id_ 
This addon provides *standalone* functionality. The addon-saphcp addon enables deploying Java EE (web profile) applications to the SAP HANA Cloud Platform (HCP): both on the local runtime and to the cloud.
        
=== Depends on
[options="header"]
|===
|Addon |Exported |Optional
|projects
|no
|no
|ui
|no
|no
|configuration
|no
|no
|===

== Setup
You should download the source code of this addon, build it with Maven (Maven 3.1+ and Java 7 are required) and then install it into your existing Forge installation like that:
[source,console]
----
forge --install com.sap.cloud:forge-addon,2.0.0-SNAPSHOT
----
Your Forge installation should be at least version 2.1.1, due to fixes in the configuration addon, that were introduced in this release. More information on installing Forge can be found on the project Github page: https://github.com/forge/core

== Features

Setting up the SAP HCP Addon:: 
You should tell Forge where your SAP HCP SDK is located, which is your user name and account. You can do that from the command line:
[source,console]
----
saphcp-setup --sdkLocation <sdk-location> --userName <user-name> --account <account>
----
or in the Forge menu in your IDE (Ctrl+5), choose *SAPHCP: Setup*.

This command is only available if you are in the context of a web project. It will check whether your SDK has a local runtime installed and if not, Forge will install it for you.

Starting and stopping the local runtime:: 
Once you have set up your SAP HANA Cloud Platform addon, you can start and stop the local runtime:
[source,console]
----
saphcp-start-local-runtime
saphcp-stop-local-runtime
----
Or alternatively choose *SAPHCP: Start Local Runtime* and *SAPHCP: Stop Local Runtime* respectively form the Forge menu in the IDE.

Deploying:: 
The essence of the SAP HCP Forge addon is the deployment part. After you have built your Java EE application you can deploy it both on the local runtime and to your cloud account. The command for the first operation is:
[source,console]
----
saphcp-deploy-locally
----
Or from the IDE: *SAPHCP: Deploy Locally*

The command for cloud deployment is:
[source,console]
----
saphcp-deploy
----
And respectively *SAPHCP: Deploy* from the IDE.

As for security reasons Forge does not store your user password, you will be prompted to enter it upon every cloud deploy request. Forge will then stop the remote application, deploy it and start it again.